services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "6A2L6cd98p"
      ACCEPT_EULA: "Y"
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db		
    ports:
      - "8080:80"

  tests: 
    image: mrexpen/planet_olymp_phase1
    pull_policy: always
    ports:
      - "8090:8080"
    depends_on:
      - webapi
    environment:
      SERVER_URL: http://webapi:80
      STAGE: all
